uint8 command
uint8 custom

uint8 CMD_TAKEOFF = 1
uint8 CMD_LAND = 2
uint8 CMD_MANUAL = 3
uint8 CMD_AUTO = 4
uint8 CMD_CLEAR_WAYPOINTS = 5
uint8 CMD_HALT = 20
uint8 CMD_GOTO = 21
uint8 CMD_BASE_MODE = 10
uint8 CMD_CUSTOM_MODE = 11

uint8 MAV_MODE_PREFLIGHT = 0
uint8 MAV_STABILIZE_DISARMED = 1
uint8 MAV_STABILIZE_ARMED = 2
uint8 MAV_MANUAL_DISARMED = 3
uint8 MAV_MANUAL_ARMED = 4
uint8 MAV_GUIDED_DISARMED = 5
uint8 MAV_GUIDED_ARMED = 6
uint8 MAV_AUTO_DISARMED = 7
uint8 MAV_AUTO_ARMED = 8
uint8 MAV_TEST_DISARMED = 9
uint8 MAV_TEST_ARMED = 10
---
bool result
