# This service currently only works for AR.Drones
uint8 camera # id for camera to activate

uint8 UNKNOWN   = 0 # used to indicate that the current active camera is unknown
uint8 FRONT     = 1 # use the front HD camera
uint8 BOTTOM    = 2 # use the bottom SVGA camera
---
Error status        # indicates success or failure of operation
